###################################################################################
# Basics
AUTHOR             = "cup"
SITENAME           = "cup's cupboard"

#SITEURL            = "" # "https://cup.nekoweb.org"
PATH               = 'content'
THEME              = 'themes/theme'
DEFAULT_PAGINATION = 10

TIMEZONE           = 'America/Boise'
DEFAULT_LANG       = 'en'

###################################################################################
# Unknown (generated by default)
FEED_ALL_ATOM         = None
CATEGORY_FEED_ATOM    = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM      = None
AUTHOR_FEED_RSS       = None

###################################################################################
# General hyperlinks
LINKS = (
    ("Name", "Link"),
)

SOCIAL = (
    ("Name", "Link"),
)

###################################################################################
# Custom stuff
DEFAULT_DATE        = None
PLUGIN_PATHS        = ['pelican-plugins']
PLUGINS             = ['render_math']
EXTRA_PATH_METADATA = {"images/favicon.ico": {"path": "favicon.ico"}}
AUTHOR_SAVE_AS      = ""
AUTHORS_SAVE_AS     = ""

## Move to blog directory
OUTPUT_PATH = "output/blog/"

SITEURL = "/blog"
RELATIVE_URLS = True

ARTICLE_URL = "posts/{slug}.html"
ARTICLE_SAVE_AS = "posts/{slug}.html"

PAGE_URL = "pages/{slug}.html"
PAGE_SAVE_AS = "pages/{slug}.html"

CATEGORY_URL = "category/{slug}.html"
CATEGORY_SAVE_AS = "category/{slug}.html"

TAG_URL = "tag/{slug}.html"
TAG_SAVE_AS = "tag/{slug}.html"

ARCHIVES_SAVE_AS = "archives.html"

###################################################################################