name: Deploy to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build folder
        run: |
          mkdir -p build
          find . \
            -path './.git' -prune -o \
            -path './.github' -prune -o \
            -path './build' -prune -o \
            -type f \
            -exec cp --parents {} build/ \;

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@main
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: './build'
          DEPLOY_DIR: '/'
          CLEANUP: 'False'
          DELAY: '2'
          NEKOWEB_PAGENAME: 'cup'